[project]
name = "barkup"
version = "0.1.0"
description = "Barkup is a Python-based CLI tool for automating personal backups to local and cloud storage with support for Google Drive."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = "src"
